- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
    - name: Update pacman
      become: true
      community.general.pacman:
        update_cache: true
        upgrade: true
        state: present
      tags:
        - install
  tasks:
    - import_tasks: tasks-arch/core.yml
    - import_tasks: tasks-arch/programming.yml
    - import_tasks: tasks-arch/git.yml
    - import_tasks: tasks-arch/ssh.yml
    - import_tasks: tasks-arch/zsh.yml
    - import_tasks: tasks-arch/dotfiles.yml
    - import_tasks: tasks-arch/node.yml
    - import_tasks: tasks-arch/npm-packages.yml
    - import_tasks: tasks-arch/nvim.yml
    - import_tasks: tasks-arch/lsp.yml
    - import_tasks: tasks-arch/docker.yml
