#!/usr/bin/env bash

HOME=/home/zellione
USER=zellione

sudo apt install software-properties-common
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt install ansible

ansible-playbook local.yml -t install --ask-vault-pass --ask-become-pass
