- name: Add Docker GPG apt key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present
  tags:
    - docker

- name: Update apt and install docker-ce
  become: true
  apt:
    name: docker-ce
    state: latest
    update_cache: true
  tags:
    - docker

- name: Create group Docker
  become: true
  group:
    name: docker
    state: present
  tags:
    - docker

- name: Add user to group
  become: true
  user:
    name: zellione
    groups: docker
    append: yes
  tags:
    - docker
