- name: install node
  become: true
  apt:
    name: ['nodejs', 'npm']
  tags:
    - node
    - install

- name: Install n
  become: true
  npm:
    name: n
    global: true
  tags:
    - node
    - install

- name: n 18
  become: true
  shell: n 18
  tags:
    - node
    - install
