- name: Add Sury PHP APT Repository
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
  tags:
    - install
    - php
- name: Install PHP Packages
  become: true
  apt:
    name: ["php8.2-cli", "php8.2-fpm", "php8.2-bcmath", "php8.2-xml", "php8.2-zip", "php8.2-intl", "php8.2-ldap", "php8.2-gd", "php8.2-bz2", "php8.2-curl", "php8.2-mbstring", "php8.2-pgsql"]
  tags:
    - install
    - php
