- name: kdenlive ppa (ppa:kdenlive/kdenlive-stable)
  become: true
  apt_repository:
   repo: ppa:kdenlive/kdenlive-stable
   state: present
   update_cache: True
  tags:
    - productivity

- name: Install packages
  become: true
  apt:
    name: [ "tmux", "fzf", "tldr", "ripgrep" ]
  tags:
    - productivity

- name: Install TPM (TMUX plugin manager)
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - productivity

- name: Install UI packages
  become: true
  apt:
    name:
      - wireshark
      - kdenlive
      - xclip
      - screenkey
      - shutter
      - gimp
  tags:
    - ui
    - productivity

- name: Install console tools
  become: true
  apt:
    name:
      - jq
  tags:
  - productivity
  - console
