- name: Install zsh
  become: true
  apt: name=zsh
  tags:
    - zsh
    - install

- name: Change shell
  become: true
  user:
    name: "zellione"
    shell: /bin/zsh
  tags:
    - zsh
    - install

- name: Install ohmyzsh (please don't tell people i use this)
  shell: if ! -d ~/.oh-my-zsh; then curl -L https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh; fi
  tags:
    - zsh
    - install

- name: Install the zsh plugin autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - zsh
    - install
