- name: Directory
  stat:
    path: /Applications/Docker.app
  register: docker_dir
  tags:
    - docker

- name: Install Docker
  community.general.homebrew:
    name: homebrew/cask/docker
    state: present
  when: "docker_dir.stat.exists == false"
  tags:
    - docker
