- name: Tab Yabai Repo
  community.general.homebrew_tap:
    name: koekeishiya/formulae
  tags:
    - yabai

- name: Install Yabai
  community.general.homebrew:
    name:
      - koekeishiya/formulae/yabai
      - koekeishiya/formulae/skhd
    state: latest
  tags:
    - yabai

- name: Start Yabai
  shell: "yabai --start-service"
  tags:
    - yabai

- name: Start SKHD
  shell: "skhd --start-service"
  tags:
    - yabai
