#!/usr/bin/env bash

set -e

HOME=/Users/snagels
USER=snagels

if [ ! -f /usr/local/bin/brew ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew update
brew install ansible
ansible-galaxy collection install community.general

ansible-playbook local.yml --ask-become-pass
