- name: Install Essential core packages
  become: true
  community.general.pacman:
    name:
      - zip
      - man-db
      - mesa-utils
      - prettier
      - bc
    state: latest
  tags:
    - core

- name: Install core packages for development
  become: true
  community.general.pacman:
    name:
      - base-devel
      - cmake
      - unzip
      - ninja
      - meson
      - curl
      - git
      - pkgconf
      - gettext
    state: latest
  tags:
    - core

- name: Download yay from AUR Repository
  ansible.builtin.git:
    repo: 'https://aur.archlinux.org/yay.git'
    dest: "{{ personal }}/yay"
  tags:
    - core

- name: Yay Directory
  stat:
    path: /usr/bin/yay
  register: yay_dir
  tags:
    - core

- name: Build and install yay
  shell: "cd {{ personal }}/yay && makepkg -si --noconfirm"
  when: "yay_dir.stat.exists == false"
  tags:
    - core

- name: Install databases
  become: true
  community.general.pacman:
    name:
      - redis
      - mariadb-clients
    state: latest
  tags:
    - core
    - databases

- name: Install community databases packages
  become: yes
  become_user: aur_builder
  aur:
    name:
      - mongodb-bin
      - mongosh-bin
    use: yay
    state: latest
  tags:
    - core
    - databases

- name: Install core packages for connectivity
  become: true
  community.general.pacman:
    name:
      - openssh
      - curl
      - wget
      - wireshark-qt
      - networkmanager
      - network-manager-applet
      - openvpn
      - inetutils
      - smbclient
      - freerdp2
      - rsync
      - aws-cli
    state: latest
  tags:
    - core
    - connectivity

- name: Install core packages for productivity
  become: true
  community.general.pacman:
    name:
      - fzf
      - tmux
      - ripgrep
      - wl-clipboard
      - xclip
      - tldr
      - screenkey
      - shutter
      - kdenlive
      - gimp
      - less
      - most
      - bat
      - lsof
      - htop
      - moreutils
      - neofetch
      - lazygit
      - github-cli
    state: latest
  tags:
    - core
    - productivity

- name: Install core utility packages
  become: true
  community.general.pacman:
    name:
      - dust
      - powertop
      - btop
      - eza

- name: Install core packages for pentesting
  become: true
  community.general.pacman:
    name:
      - nmap
      - john
    state: latest
  tags:
    - core
    - pentesting

- name: Install community packages for pentesting
  become: yes
  become_user: aur_builder
  aur:
    name:
      - wordlists
      - ruby-evil-winrm
      - responder
    use: yay
    state: latest
  tags:
    - core
    - pentesting


- name: Install TPM (TMUX plugin manager)
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - core
    - productivity


# - name: Install NVIDIA Drivers
#   become: true
#   community.general.pacman:
#     name:
#       - nvidia
#       - nvidia-settings
#       - nvidia-utils
#       - cuda
#       - cuda-tools
#       - cudnn
#   tags:
#     - core
#     - drivers

- name: Install pipewire and replace pulseaudio
  become: true
  community.general.pacman:
    name:
      - wireplumber
      - pipewire-pulse
      - pipewire-alsa
      - pipewire-x11-bell
      - pipewire-zeroconf
  tags:
    - core
    - drivers

- name: Activate pipewire pulse
  ansible.builtin.systemd:
    name: pipewire-pulse
    state: started
    enabled: true
    scope: user
  tags:
    - core
    - drivers
  ignore_errors: true

- name: Activate pipewire
  ansible.builtin.systemd:
    name: pipewire
    state: started
    enabled: true
    scope: user
  tags:
    - core
    - drivers
  ignore_errors: true


- name: Install Browsers
  become: true
  community.general.pacman:
    name:
      - chromium
      - firefox
    state: latest
  tags:
    - core
    - browsers

- name: Download or Update wlogout Repository
  ansible.builtin.git:
    repo: "https://github.com/ArtsyMacaw/wlogout.git"
    recursive: yes
    dest: "{{ personal }}/wlogout"
  tags:
    - core
    - ui

- name: Build WLogout
  shell: "cd {{ personal }}/wlogout && meson build && ninja -C build"
  tags:
    - core
    - ui

- name: Install WLogout
  become: true
  shell: "cd {{ personal }}/wlogout && ninja -C build install"
  tags:
    - core
    - ui
