- name: Install Docker
  become: true
  community.general.pacman:
    name: docker
    state: latest
  tags:
    - docker

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    state: present
  tags:
    - docker

- name: Enable Docker
  become: true
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true
  tags:
    - docker
  ignore_errors: yes
