- name: Update from git
  ansible.builtin.git:
    repo: "https://github.com/ryanoasis/nerd-fonts.git"
    dest: "{{ ansible_env.HOME }}/nerd-fonts"
    depth: 1
    force: yes
  tags:
    - nerd-fonts
    - fonts

- name: Select fonts to install
  ansible.builtin.find:
    recurse: yes
    use_regex: yes
    paths: "{{ ansible_env.HOME }}/nerd-fonts/patched-fonts"
    patterns:
      - '^.*?((?!Windows).)*?\.ttf$'
  register: fonts_to_install
  tags:
    - nerd-fonts
    - fonts

- name: Ensure .fonts directory exists.
  file:
    dest: "{{ ansible_env.HOME }}/.fonts"
    mode: 0755
    state: directory
  tags:
    - nerd-fonts
    - fonts

- name: Install fonts
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.fonts/{{ item.path | basename }}"
    src: "{{ item.path }}"
    remote_src: yes
    force: false
  loop: "{{ fonts_to_install.files }}"
  notify:
    - update font cache
  tags:
    - nerd-fonts
    - fonts
