- name: Install Terminal emulator
  become: true
  community.general.pacman:
    name:
      - kitty
  tags:
    - hyprland

- name: Install Hyprland Dependencies
  become: true
  community.general.pacman:
    name:
      - gobject-introspection
      - gtk-layer-shell
      - scdoc
      - python-pywal
      - jq
      - thunar
      - pamixer
      - pipewire
      - pipewire-alsa
      - pipewire-pulse
      - pipewire-audio
      - wireplumber
      - bluez
      - bluez-utils
      - blueman
      - gnome-system-monitor
      - polkit-gnome
      - imagemagick
      - cliphist
      - grim
      - gvfs
      - gvfs-mtp
      - kvantum
      - network-manager-applet
      - pavucontrol
      - playerctl
      - qt5ct
      - qt6ct
      - qt6-svg
      - slurp
      - swappy
      - swayidle
      - wl-clipboard
      - xdg-user-dirs
      - xdg-utils
      - yad
      - brightnessctl
      - eog
      - mousepad
      - mpv
      - mpv-mpris
      - nvtop
      - pacman-contrib
      - yt-dlp
  tags:
    - hyprland

- name: Install Hyprland Fonts
  become: true
  community.general.pacman:
    name:
      - adobe-source-code-pro-fonts
      - noto-fonts-emoji
      - otf-font-awesome
      - ttf-droid
      - ttf-jetbrains-mono
      - ttf-jetbrains-mono-nerd

- name: Install Hyprland community Dependencies
  become: yes
  become_user: aur_builder
  aur:
    name:
      - swww
      - swaync
      - cava
      - rofi-lbonn-wayland-git
      - swaylock-effects-git
      - nwg-look-bin
      - waybar-mpris-git
    use: yay
    state: latest
  tags:
    - hyprland


- name: Install Waybar
  become: true
  community.general.pacman:
    name:
      - waybar
  tags:
    - hyprland

- name: Install Hyprland
  become: true
  community.general.pacman:
    name:
      - wl-clipboard
      - hyprland
      - hyprcursor
  tags:
    - hyprland

- name: Download or Update wlogout Repository
  ansible.builtin.git:
    repo: "https://github.com/ArtsyMacaw/wlogout.git"
    recursive: yes
    dest: "{{ personal }}/wlogout"
  tags:
    - hyprland

- name: Build WLogout
  shell: "cd {{ personal }}/wlogout && meson build && ninja -C build"
  tags:
    - hyprland

- name: Install WLogout
  become: true
  shell: "cd {{ personal }}/wlogout && ninja -C build install"
  tags:
    - hyprland

- name: Activate Bluetooth daemon
  become: true
  systemd:
    name: bluetooth
    enabled: yes
    state: started
  tags:
    - hyprland

- name: Create input group if not exists
  become: true
  ansible.builtin.group:
    name: input
    state: present
  tags:
    - hyprland

- name: Add user to input group
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    groups: input
    state: present
    append: yes
  tags:
    - hyprland

- name: Install sddm
  become: true
  community.general.pacman:
    name:
      - sddm
      - qt5-graphicaleffects
      - qt5-quickcontrols2
      - qt5-svg
  tags:
    - hyprland

- name: Enable sddm
  become: true
  systemd:
    name: sddm
    enabled: yes
    state: started
  tags:
    - hyprland

- name: Create sddm directory
  become: true
  ansible.builtin.file:
    path: /etc/sddm.conf.d
    state: directory
  tags:
    - hyprland

- name: Create wayland session directory
  become: true
  ansible.builtin.file:
    path: /usr/share/wayland-sessions
    state: directory
  tags:
    - hyprland

- name: Create sddm themes directory
  become: true
  ansible.builtin.file:
    path: /usr/share/sddm/themes
    state: directory
  tags:
    - hyprland

- name: Checkout sddm theme
  become: true
  ansible.builtin.git:
    repo: "https://github.com/JaKooLit/simple-sddm.git"
    dest: "/usr/share/sddm/themes/simple-sddm"
  tags:
    - hyprland

- name: Copy sddm config file to sddm config directory
  become: true
  ansible.builtin.copy:
    src: "../configs/sddm/10-theme.conf"
    dest: /etc/sddm.conf.d/10-theme.conf
  tags:
    - hyprland

- name: Install GTK Theme
  become: true
  community.general.pacman:
    name:
      - unzip
      - gtk-engine-murrine
  tags:
    - hyprland

- name: Clone Tokyo Theme GTK themes and icons repository
  ansible.builtin.git:
    repo: "https://github.com/JaKooLit/GTK-themes-icons.git"
    dest: "{{ personal }}/GTK-themes-icons"
  tags:
    - hyprland

- name: Ensure auto-extract script is executable
  shell: "chmod +x {{ personal }}/GTK-themes-icons/auto-extract.sh"
  tags:
    - hyprland

- name: Run Autoextract command
  shell: "cd {{ personal }}/GTK-themes-icons && ./auto-extract.sh"
  tags:
    - hyprland

- name: Clone Arch-Hyprland repository
  ansible.builtin.git:
    repo: "https://github.com/JaKooLit/Arch-Hyprland.git"
    dest: "{{ personal }}/Arch-Hyprland"
  tags:
    - hyprland

- name: Extract Bibata-Modern-Ice cursor theme
  shell: "cd {{ personal }}/Arch-Hyprland/assets && tar -xf Bibata-Modern-Ice.tar.xz -C ~/.icons"
  tags:
    - hyprland
