- name: Install Terminal emulator
  become: true
  community.general.pacman:
    name:
      - kitty
  tags:
    - hyprland

- name: Install Hyprland Dependencies
  become: true
  community.general.pacman:
    name:
      - gobject-introspection
      - gtk-layer-shell
      - scdoc
      - python-pywal
      - jq
      - pamixer
      - bluez
      - bluez-utils
      - blueman
  tags:
    - hyprland

- name: Install Hyprland community Dependencies
  become: yes
  become_user: aur_builder
  aur:
    name: swww
    use: yay
    state: latest
  tags:
    - hyprland


- name: Install Waybar
  become: true
  community.general.pacman:
    name:
      - waybar
  tags:
    - hyprland

- name: Install Hyprland
  become: true
  community.general.pacman:
    name:
      - wl-clipboard
      - hyprland
  tags:
    - hyprland

- name: Download or Update wlogout Repository
  ansible.builtin.git:
    repo: "https://github.com/ArtsyMacaw/wlogout.git"
    recursive: yes
    dest: "{{ personal }}/wlogout"
  tags:
    - hyprland

- name: Build WLogout
  shell: "cd {{ personal }}/wlogout && meson build && ninja -C build"
  tags:
    - hyprland

- name: Install WLogout
  become: true
  shell: "cd {{ personal }}/wlogout && ninja -C build install"
  tags:
    - hyprland

- name: Activate Bluetooth daemon
  become: true
  systemd:
    name: bluetooth
    enabled: yes
    state: started
  tags:
    - hyprland
