- name: Install Yarn
  become: true
  npm:
    name: yarn
    global: yes
  tags:
    - node

- name: Install PNPM
  become: true
  npm:
    name: pnpm
    global: yes
  tags:
    - node

- name: Install eslint
  become: true
  npm:
    name: eslint
    global: yes
  tags:
    - node

- name: Install Typescript server
  become: true
  npm:
    name: typescript-language-server
    global: yes
  tags:
    - node

- name: Install Typescript
  become: true
  npm:
    name: typescript
    global: yes
  tags:
    - node

- name: Install TS-Node
  become: true
  npm:
    name: ts-node
    global: yes
  tags:
    - node
