- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - neovim

- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - neovim

- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"
  tags:
    - neovim

- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - neovim

- name: Neovim Plugin Development 1
  become: true
  community.general.pacman:
    name: luarocks
    state: latest
  tags:
    - neovim

- name: Neovim Plugin Development 2 luacheck
  become: true
  shell: luarocks install luacheck
  tags:
    - neovim
