- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - ssh

- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
    force: no
  when: "dest_key is not file"
  tags:
    - dotfiles
    - ssh

- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_pub_key }}"
    mode: 0644
    force: no
  when: "dest_pub_key is not file"
  tags:
    - dotfiles
    - ssh
