- name: Install zsh
  become: true
  community.general.pacman:
    name: zsh
  tags:
    - zsh

- name: Change shell
  become: true
  user:
    name: "zellione"
    shell: /bin/zsh
  tags:
    - zsh

- name: Install ohmyzsh (please don't tell people i use this)
  shell: if ! -d ~/.oh-my-zsh; then curl -L https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh; fi
  args:
    creates: ~/.oh-my-zsh
  tags:
    - zsh

- name: Install the zsh plugin autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - zsh

- name: Install the zsh plugin syntax highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  tags:
    - zsh

- name: Install the zsh custom theme powerlevel10k
  ansible.builtin.git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: "~/.oh-my-zsh/custom/themes/powerlevel10k"
  tags:
    - zsh

- name: Install the zsh fzf git mod
  ansible.builtin.git:
    repo: 'https://github.com/junegunn/fzf-git.sh.git'
    dest: "~/tools/fzf-git.sh.git"
  tags:
    - zsh

- name: Install the zsh plugin npm autocompletion
  ansible.builtin.git:
    repo: 'https://github.com/grigorii-zander/zsh-npm-scripts-autocomplete.git'
    dest: "~/.oh-my-zsh/custom/plugins/zsh-npm-scripts-autocomplete"
  tags:
    - zsh
