- name: Install Essential core packages
  become: true
  community.general.pacman:
    name:
      - zip
    state: latest
  tags:
    - install
    - core

- name: Install core packages for development
  become: true
  community.general.pacman:
    name:
      - base-devel
      - cmake
      - unzip
      - ninja
      - curl
      - git
      - pkgconf
      - gettext
    state: latest
  tags:
    - install
    - core

- name: Install core packages for connectivity
  become: true
  community.general.pacman:
    name:
      - openssh
      - curl
      - wget
      - wireshark-qt
      - networkmanager
      - network-manager-applet
    state: latest
  tags:
    - install
    - core

- name: Install core packages for productivity
  become: true
  community.general.pacman:
    name:
      - fzf
      - tmux
      - ripgrep
      - wl-clipboard
      - xclip
      - tldr
      - screenkey
      - shutter
      - kdenlive
      - gimp
      - less
      - lsof
      - htop
      - moreutils
    state: latest
  tags:
    - install
    - core
    - productivity

- name: Download yay from AUR Repository
  ansible.builtin.git:
    repo: 'https://aur.archlinux.org/yay.git'
    dest: "{{ personal }}/yay"
  tags:
    - install
    - core

- name: Build and install yay
  shell: "cd {{ personal }}/yay && makepkg -si --noconfirm"
  tags:
    - install
    - core

- name: Install NVIDIA Drivers
  become: true
  community.general.pacman:
    name:
      - nvidia
      - nvidia-settings
      - nvidia-utils
      - cuda
      - cuda-tools
      - cudnn
