- name: Install wayland
  become: true
  community.general.pacman:
    name:
      - wayland
      - xorg-xwayland
      - alacritty
    state: latest
  tags:
    - install
    - ui

- name: Install gdm
  become: true
  community.general.pacman:
    name: gdm
    state: latest
  tags:
    - install
    - ui

- name: Install gnome
  become: true
  community.general.pacman:
    name: gnome
    state: latest
  tags:
    - install
    - ui

- name: Install gnome shell extension -> forge
  become: yes
  become_user: aur_builder
  aur:
    name: gnome-shell-extension-forge
    use: yay
    state: latest
  tags:
    - install
    - ui

- name: Install gnome shell extension -> just perfection
  become: yes
  become_user: aur_builder
  aur:
    name: gnome-shell-extension-just-perfection-desktop
    use: yay
    state: latest
  tags:
    - install
    - ui

# - name: Install gnome shell extension -> search light
#   become: yes
#   become_user: aur_builder
#   aur:
#     name:  gnome-shell-extension-search-light-git
#     use: yay
#     state: latest
#   tags:
#     - install
#     - ui

- name: Checkout gnome shell extension -> search light
  ansible.builtin.git:
    repo: 'https://github.com/icedman/search-light'
    dest: "{{ personal }}/search-light"
    version: g44
  tags:
    - install
    - ui

- name: Built  gnome shell extension -> search light
  ansible.builtin.shell:
    cmd: make
    chdir: "{{ personal }}/search-light"
  tags:
    - install
    - ui

- name: Checkout gnome shell extension -> AATWS (Advanced Alt-Tab Window Switcher)
  ansible.builtin.git:
    repo: 'https://github.com/G-dH/advanced-alttab-window-switcher.git'
    dest: "{{ personal }}/aatws"
  tags:
    - install
    - ui

- name: Built  gnome shell extension -> AATWS (Advanced Alt-Tab Window Switcher)
  ansible.builtin.shell:
    cmd: make
    chdir: "{{ personal }}/aatws"
  tags:
    - install
    - ui

- name: Install gnome shell extension -> AATWS (Advanced Alt-Tab Window Switcher)
  ansible.builtin.shell:
    cmd: "make install && gnome-extensions install --force advanced-alt-tab@G-dH.github.com.zip"
    chdir: "{{ personal }}/aatws"
  tags:
    - install
    - ui

- name: Install gradience
  become: yes
  become_user: aur_builder
  aur:
    name: gradience
    use: yay
    state: latest
  tags:
    - install
    - ui

- name: Install gnome shell extension -> Arc Menu
  become: yes
  become_user: aur_builder
  aur:
    name: gnome-shell-extension-arc-menu
    use: yay
    state: latest
  tags:
    - install
    - ui

- name: Install gnome shell extension -> Dash to Panel
  become: yes
  become_user: aur_builder
  aur:
    name: gnome-shell-extension-dash-to-panel
    use: yay
    state: latest
  tags:
    - install
    - ui

- name: Install gnome shell extension -> AppIndicators
  become: yes
  become_user: aur_builder
  aur:
    name: gnome-shell-extension-appindicator
    use: yay
    state: latest
  tags:
    - install
    - ui

- name: Install gnome shell extension -> Gnome Tweaks
  become: true
  community.general.pacman:
    name: gnome-tweaks
    state: latest
  tags:
    - install
    - ui

- name: Install gnome shell extension -> Vitals
  become: yes
  become_user: aur_builder
  aur:
    name: gnome-shell-extension-vitals
    use: yay
    state: latest
  tags:
    - install
    - ui

- name: Install gnome shell extension -> Pano
  become: yes
  become_user: aur_builder
  aur:
    name: gnome-shell-extension-pano
    use: yay
    state: latest
  tags:
    - install
    - ui

- name: Install gnome shell extension -> Blur my Shell
  become: yes
  become_user: aur_builder
  aur:
    name: gnome-shell-extension-blur-my-shell
    use: yay
    state: latest
  tags:
    - install
    - ui

- name: Install gnome shell extension -> OpenWeather
  become: yes
  become_user: aur_builder
  aur:
    name: gnome-shell-extension-openweather
    use: yay
    state: latest
  tags:
    - install
    - ui

- name: Install gdm-settings
  become: yes
  become_user: aur_builder
  aur:
    name: gdm-settings
    use: yay
    state: latest
  tags:
    - install
    - ui

- name: Load saved gnome configuration
  shell: "dconf load / < gnome-config/dconf-settings.ini"
