#!/usr/bin/env bash

HOME=/home/zellione
USER=zellione


mkdir -p ~/.ansible/plugins/modules
curl -o ~/.ansible/plugins/modules/aur.py https://raw.githubusercontent.com/kewlfft/ansible-aur/master/plugins/modules/aur.py

ansible-playbook local.yml --ask-vault-pass
